name: deploy-to-production
on:
  # release:
  #   types: [published]
  push:
    branches:
    - master
jobs:
  deploy-to-production:
    environment: release-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: "placeholder-text"

    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Rebuild containers with docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/admin-ts/
          export NEXT_PUBLIC_HASURA_URL=${{secrets.NEXT_PUBLIC_HASURA_URL}} &&
          export NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}
          docker-compose up -d --build
